a = int(input())
b = int(input())
c = int(input())
d = int(input())
e = int(input())
f = int(input())
x = (a * 3600)
y = (b * 60)
time1 = (x + y + c)
v = (d * 3600)
w = (e * 60)
time2 = (v + w + f)

print(time2 - time1)